### ISSUE TITLE
Saving recipe to List/Cookbook

### ISSUE THREAD

**Issue by nhilikeknee** [cse110-fa21-group23/cse110-fa21-group23#16]
As a user, I want to browse recipes and save them so I can revisit the recipes later at a more convenient time.
Task: create functionality (JS) that allows users to save an existing recipe to a Saved list. When user clicks on the List (HTML), all of the recipes previously saved to that list should display (as Recipe Cards, refer to Karina or Lab 6 for template). Note: we’re not creating different Lists/Cookbooks yet, we’re just allowing users to add/save recipes to one default/hardcoded list for now.
Assigned to: Chris & Flynn

**Comment by humanmanwhoisnotdead** [comment]
I'm not sure how we're supposed to do documentation so I'm leaving a comment here. 
Did some work on this yesterday on Monday with my Flynn and just tidied up the code somewhat today; I pushed both of those but didn't make any pull requests as it isn't done yet.
On the cookbook display, we only coded it to show list names and not any recipes since if the user has too many lists showing the recipes would make it hard for the user to find anything. We may want to have 2 different display modes here based on the number of lists a user can have or simply restrict their list size.
